# Site Settings
title: "Dive's Data Analysis / Data Engineer Blog"
name: "diveintoive6"
description: "데이터 분석 / 데이터 엔지니어링 블로그"
url: "https://diveintoive6.github.io"
baseurl: "" 

# Minimal Mistakes 테마 연결
remote_theme: mmistakes/minimal-mistakes

# Plugins 설정 (필수)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 기타 설정
minimal_mistakes_skin: "default"
locale: "ko-KR"

# Date Format
date_format: "%Y-%m-%d %H:%M"

# Author Settings
author:
  name: "diveintoive6"      # 또는 원하는 익명 닉네임
  avatar: ""                # 프로필 사진이 없다면 비워두기 (기본 아이콘 또는 빈 화면)
  bio: "Data Analysis & Engineering" # 간단한 한 줄 소개 (직함 대신 관심사 기록)
  location: "South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/diveintoive6"
